import React, { createContext, useContext, useState } from "react";

export const translations = {
  en: {
    dir: "ltr",
    Dashboard: "Dashboard",
    Datasets: "Datasets",
    Metadata: "Metadata",
    "Data Quality": "Data Quality",
    Insights: "Insights",
    Governance: "Governance",
    Reports: "Reports",
    "Activity Log": "Activity Log",
    Admin: "Admin",
    "Enterprise Platform": "Enterprise Platform",
    Navigation: "Navigation",
    Administrator: "Administrator",
    Member: "Member",
    "Profile Settings": "Profile Settings",
    "Sign Out": "Sign Out",
    "Data Overview": "Data Overview",
    "Welcome to DataHarbor": "Welcome to DataHarbor",
    "Your organization has": "Your organization has",
    "datasets": "datasets",
    "with": "with",
    "records": "records",
    "avg quality": "avg quality",
    "Across": "Across",
    "Total Datasets": "Total Datasets",
    "Total Records": "Total Records",
    "Avg Quality Score": "Avg Quality Score",
    "Quality Reports": "Quality Reports",
    "datasets in total": "datasets in total",
    "Upload Dataset": "Upload Dataset",
    "Activity Log Title": "Activity Log",
    "Track all actions across the platform": "Track all actions across the platform",
    "Search activity...": "Search activity...",
    "All Actions": "All Actions",
    "No activity found": "No activity found",
    "active": "active",
    "rated Good": "rated Good",
    "need attention": "need attention",
    // Metadata page
    "Metadata Management": "Metadata Management",
    "View and manage metadata for all datasets": "View and manage metadata for all datasets",
    "Search by name or tags...": "Search by name or tags...",
    "No datasets found": "No datasets found",
    "Edit Metadata": "Edit Metadata",
    "Edit": "Edit",
    "Save": "Save",
    "Cancel": "Cancel",
    // Reports page
    "Reports Title": "Reports",
    "Generate and manage data reports": "Generate and manage data reports",
    "Generate Report": "Generate Report",
    "No reports generated yet": "No reports generated yet",
    "Generate Report dialog": "Generate Report",
    "Report Type": "Report Type",
    "Select type": "Select type",
    "Dataset (optional)": "Dataset (optional)",
    "All Datasets": "All Datasets",
    "Generate": "Generate",
    // Data Quality page
    "Data Quality Monitoring": "Data Quality Monitoring",
    "Monitor data quality across all datasets": "Monitor data quality across all datasets",
    "Search datasets...": "Search datasets...",
    "No quality reports found": "No quality reports found",
    "Avg Quality Score label": "Avg Quality Score",
    // Governance page
    "Data Governance": "Data Governance",
    "Governance Dashboard": "Governance Dashboard",
    "Catalog Overview": "Catalog Overview",
    "Quality Health": "Quality Health",
    "Org Settings": "Org Settings",
    // Admin page
    "Admin Panel": "Admin Panel",
    "Platform management and monitoring": "Platform management and monitoring",
    "Access Restricted": "Access Restricted",
    "Admin privileges are required to view this page.": "Admin privileges are required to view this page.",
    "Users": "Users",
    "Datasets": "Datasets",
    "Quality Issues": "Quality Issues",
    "Activity": "Activity",
    "Statistics": "Statistics",
    // AdminStats
    "Total Users": "Total Users",
    "Activity Events": "Activity Events",
    "Good Quality": "Good Quality",
    "Poor Quality Issues": "Poor Quality Issues",
    // UserManagement
    "Search users…": "Search users…",
    "Name": "Name",
    "Email": "Email",
    "Role": "Role",
    "Joined": "Joined",
    "Change Role": "Change Role",
    "No users found": "No users found",
    "You": "You",
    "Role updated": "Role updated",
    // AdminDatasets
    "Search datasets…": "Search datasets…",
    "Department": "Department",
    "Owner": "Owner",
    "Rows": "Rows",
    "Quality": "Quality",
    "Status": "Status",
    "Uploaded": "Uploaded",
    "No datasets found": "No datasets found",
    // AdminActivity
    "Search activity…": "Search activity…",
    "No matching activity": "No matching activity",
    "All": "All",
    // PlatformStats
    "Total Records": "Total Records",
    "Total Columns": "Total Columns",
    "Avg Quality": "Avg Quality",
    "Analyzed Datasets": "Analyzed Datasets",
    "Datasets by Department": "Datasets by Department",
    "Data Quality Distribution": "Data Quality Distribution",
    "Datasets by Category": "Datasets by Category",
    "Data Sensitivity Levels": "Data Sensitivity Levels",
    "No data": "No data",
    "No quality data yet": "No quality data yet",
    // PoorQualityReview
    "All datasets have acceptable quality": "All datasets have acceptable quality",
    "No issues to review right now.": "No issues to review right now.",
    "dataset(s) need attention": "dataset(s) need attention",
    "more warnings": "more warnings",
    "Missing": "Missing",
    "Duplicates": "Duplicates",
    "Empty cols": "Empty cols",
    "Bad dates": "Bad dates",
    "View": "View",
    // DatasetTable
    "Dataset": "Dataset",
    "Category": "Category",
    "Rows": "Rows",
    "Uploaded": "Uploaded",
    "shown": "shown",
    "dataset": "dataset",
    "datasets shown": "datasets shown",
    "No datasets found": "No datasets found",
    "Try adjusting filters": "Try adjusting your filters or upload a new dataset",
    "View Insights": "View Insights",
    "Edit Metadata": "Edit Metadata",
    "Download File": "Download File",
    "Delete": "Delete",
    // Metadata page field labels
    "Source": "Source",
    "Business Owner": "Business Owner",
    "Technical Owner": "Technical Owner",
    "Region": "Region",
    "Frequency": "Frequency",
    "Language": "Language",
    "Records": "Records",
    "No description": "No description",
    "Created": "Created",
    "Updated": "Updated",
    "Description": "Description",
    "Tags (comma-separated)": "Tags (comma-separated)",
    "Data Sensitivity": "Data Sensitivity",
    "Update Frequency": "Update Frequency",
    // DataQuality expanded
    "Missing Values": "Missing Values",
    "Duplicate Rows": "Duplicate Rows",
    "Empty Columns": "Empty Columns",
    "Invalid Dates": "Invalid Dates",
    "Invalid Numerics": "Invalid Numerics",
    "Consistency": "Consistency",
    "Warnings": "Warnings",
    "Recommendations": "Recommendations",
    "Last checked": "Last checked",
    // Governance KPIs
    "Total Datasets": "Total Datasets",
    "Metadata Complete": "Metadata Complete",
    "Missing Metadata": "Missing Metadata",
    "Quality Reports": "Quality Reports",
    "Good Quality": "Good Quality",
    "Needs Review": "Needs Review",
    "Poor Quality": "Poor Quality",
    "active": "active",
    "fully complete": "fully complete",
    "datasets OK": "datasets OK",
    "not analyzed": "not analyzed",
    "of analyzed": "of analyzed",
    "Needs immediate action": "Needs immediate action",
    "All clear": "All clear",
    "Monitor quality, metadata completeness, and catalog health across": "Monitor data quality, metadata completeness, and catalog health across",
    // Governance charts
    "Data Quality Distribution": "Data Quality Distribution",
    "Quality status breakdown across all datasets": "Quality status breakdown across all datasets",
    "No quality reports yet": "No quality reports yet",
    "Datasets by Department": "Datasets by Department",
    "Number of datasets per business unit": "Number of datasets per business unit",
    "No department data yet": "No department data yet",
    "Datasets by Category": "Datasets by Category",
    "Classification breakdown of the data catalog": "Classification breakdown of the data catalog",
    "No category data yet": "No category data yet",
    "Missing Metadata Fields": "Missing Metadata Fields",
    "Datasets missing key metadata per field": "Datasets missing key metadata per field",
    "No datasets yet": "No datasets yet",
    "Upload your first dataset to start using the governance dashboard": "Upload your first dataset to start using the governance dashboard",
    // Insights tabs
    "Data Preview": "Data Preview",
    "Charts": "Charts",
    "Quality Report": "Quality Report",
    "Column Profiles": "Column Profiles",
    "Sample Data": "Sample Data",
    "Versions": "Versions",
    "Data Lineage": "Data Lineage",
    "Back to Datasets": "Back to Datasets",
    "Download File": "Download File",
    "No dataset selected": "No dataset selected",
    "Select an existing dataset to explore its insights, or upload a new one.": "Select an existing dataset to explore its insights, or upload a new one.",
    "Browse Datasets": "Browse Datasets",
    "Select a Dataset": "Select a Dataset",
    "Dataset not found.": "Dataset not found.",
    // Report types
    "Metadata Report": "Metadata Report",
    "Data Quality Report": "Data Quality Report",
    "Dashboard Summary": "Dashboard Summary",
    "Dataset Profile": "Dataset Profile",
    // Report statuses
    "Generated": "Generated",
    "Pending": "Pending",
    "Failed": "Failed",
    // Activity Log action names
    "User Login": "User Login",
    "Dataset Uploaded": "Dataset Uploaded",
    "Dataset Updated": "Dataset Updated",
    "Dataset Deleted": "Dataset Deleted",
    "Metadata Edited": "Metadata Edited",
    "Report Exported": "Report Exported",
    "Quality Check": "Quality Check",
    "User Registered": "User Registered",
    "System": "System",
    // Dataset status
    "Active": "Active",
    "Archived": "Archived",
    "Draft": "Draft",
    "Under Review": "Under Review",
    // Dashboard Recent Datasets
    "Recently Uploaded": "Recently Uploaded",
    "Latest additions to the catalog": "Latest additions to the catalog",
    // Chart titles and subtitles
    "Datasets by Department": "Datasets by Department",
    "Number of datasets per business unit": "Number of datasets per business unit",
    "No department data yet": "No department data yet",
    "Datasets by Category": "Datasets by Category",
    "Classification breakdown of the data catalog": "Classification breakdown of the data catalog",
    "No category data yet": "No category data yet",
    "Data Quality Distribution": "Data Quality Distribution",
    "Quality status breakdown across all datasets": "Quality status breakdown across all datasets",
    "No quality reports yet": "No quality reports yet",
    "Upload Trends": "Upload Trends",
    "Datasets uploaded & average quality over last 6 months": "Datasets uploaded & average quality over last 6 months",
    "Avg Quality": "Avg Quality %",
    // Quality statuses
    "Good": "Good",
    "Needs Review": "Needs Review",
    "Poor Quality": "Poor Quality",
    // Recent Activity
    "Recent Activity": "Recent Activity",
    "Latest platform events": "Latest platform events",
    // View All
    "View All": "View All",
  },
  ar: {
    dir: "rtl",
    Dashboard: "لوحة التحكم",
    Datasets: "مجموعات البيانات",
    Metadata: "البيانات الوصفية",
    "Data Quality": "جودة البيانات",
    Insights: "الرؤى والتحليلات",
    Governance: "الحوكمة",
    Reports: "التقارير",
    "Activity Log": "سجل النشاط",
    Admin: "الإدارة",
    "Enterprise Platform": "منصة مؤسسية",
    Navigation: "التنقل",
    Administrator: "مسؤول",
    Member: "عضو",
    "Profile Settings": "إعدادات الملف الشخصي",
    "Sign Out": "تسجيل الخروج",
    "Data Overview": "نظرة عامة على البيانات",
    "Welcome to DataHarbor": "مرحباً بك في DataHarbor",
    "Your organization has": "مؤسستك لديها",
    "datasets": "مجموعة بيانات",
    "with": "تحتوي على",
    "records": "سجل",
    "avg quality": "متوسط الجودة",
    "Across": "عبر",
    "Total Datasets": "إجمالي مجموعات البيانات",
    "Total Records": "إجمالي السجلات",
    "Avg Quality Score": "متوسط درجة الجودة",
    "Quality Reports": "تقارير الجودة",
    "datasets in total": "مجموعة بيانات إجمالاً",
    "Upload Dataset": "رفع مجموعة بيانات",
    "Activity Log Title": "سجل النشاط",
    "Track all actions across the platform": "تتبع جميع الإجراءات عبر المنصة",
    "Search activity...": "ابحث عن نشاط...",
    "All Actions": "جميع الإجراءات",
    "No activity found": "لا يوجد نشاط",
    "active": "نشط",
    "rated Good": "بتقييم جيد",
    "need attention": "تحتاج مراجعة",
    // Metadata page
    "Metadata Management": "إدارة البيانات الوصفية",
    "View and manage metadata for all datasets": "عرض وإدارة البيانات الوصفية لجميع مجموعات البيانات",
    "Search by name or tags...": "ابحث بالاسم أو الوسوم...",
    "No datasets found": "لا توجد مجموعات بيانات",
    "Edit Metadata": "تعديل البيانات الوصفية",
    "Edit": "تعديل",
    "Save": "حفظ",
    "Cancel": "إلغاء",
    // Reports page
    "Reports Title": "التقارير",
    "Generate and manage data reports": "إنشاء وإدارة تقارير البيانات",
    "Generate Report": "إنشاء تقرير",
    "No reports generated yet": "لم يتم إنشاء تقارير بعد",
    "Generate Report dialog": "إنشاء تقرير",
    "Report Type": "نوع التقرير",
    "Select type": "اختر النوع",
    "Dataset (optional)": "مجموعة البيانات (اختياري)",
    "All Datasets": "جميع مجموعات البيانات",
    "Generate": "إنشاء",
    // Data Quality page
    "Data Quality Monitoring": "مراقبة جودة البيانات",
    "Monitor data quality across all datasets": "مراقبة جودة البيانات عبر جميع المجموعات",
    "Search datasets...": "ابحث عن مجموعة بيانات...",
    "No quality reports found": "لا توجد تقارير جودة",
    "Avg Quality Score label": "متوسط درجة الجودة",
    // Governance page
    "Data Governance": "حوكمة البيانات",
    "Governance Dashboard": "لوحة الحوكمة",
    "Catalog Overview": "نظرة عامة على الكتالوج",
    "Quality Health": "صحة الجودة",
    "Org Settings": "إعدادات المؤسسة",
    // Admin page
    "Admin Panel": "لوحة الإدارة",
    "Platform management and monitoring": "إدارة ومراقبة المنصة",
    "Access Restricted": "الوصول مقيد",
    "Admin privileges are required to view this page.": "يلزم صلاحيات المسؤول لعرض هذه الصفحة.",
    "Users": "المستخدمون",
    "Quality Issues": "مشاكل الجودة",
    "Activity": "النشاط",
    "Statistics": "الإحصائيات",
    // AdminStats
    "Total Users": "إجمالي المستخدمين",
    "Activity Events": "أحداث النشاط",
    "Good Quality": "جودة جيدة",
    "Poor Quality Issues": "مشاكل جودة رديئة",
    // UserManagement
    "Search users…": "ابحث عن مستخدم...",
    "Name": "الاسم",
    "Email": "البريد الإلكتروني",
    "Role": "الدور",
    "Joined": "تاريخ الانضمام",
    "Change Role": "تغيير الدور",
    "No users found": "لا يوجد مستخدمون",
    "You": "أنت",
    "Role updated": "تم تحديث الدور",
    // AdminDatasets
    "Search datasets…": "ابحث عن مجموعة بيانات...",
    "Department": "القسم",
    "Owner": "المالك",
    "Rows": "الصفوف",
    "Quality": "الجودة",
    "Status": "الحالة",
    "Uploaded": "تاريخ الرفع",
    "No datasets found": "لا توجد مجموعات بيانات",
    // AdminActivity
    "Search activity…": "ابحث عن نشاط...",
    "No matching activity": "لا يوجد نشاط مطابق",
    "All": "الكل",
    // PlatformStats
    "Total Records": "إجمالي السجلات",
    "Total Columns": "إجمالي الأعمدة",
    "Avg Quality": "متوسط الجودة",
    "Analyzed Datasets": "مجموعات محللة",
    "Datasets by Department": "المجموعات حسب القسم",
    "Data Quality Distribution": "توزيع جودة البيانات",
    "Datasets by Category": "المجموعات حسب الفئة",
    "Data Sensitivity Levels": "مستويات حساسية البيانات",
    "No data": "لا توجد بيانات",
    "No quality data yet": "لا توجد بيانات جودة بعد",
    // PoorQualityReview
    "All datasets have acceptable quality": "جميع المجموعات ذات جودة مقبولة",
    "No issues to review right now.": "لا توجد مشاكل للمراجعة حالياً.",
    "dataset(s) need attention": "مجموعة بيانات تحتاج مراجعة",
    "more warnings": "تحذيرات إضافية",
    "Missing": "مفقود",
    "Duplicates": "مكررات",
    "Empty cols": "أعمدة فارغة",
    "Bad dates": "تواريخ خاطئة",
    "View": "عرض",
    // OrgSettings sections
    "Departments": "الأقسام",
    "Dataset Categories": "فئات المجموعات",
    "Tags": "العلامات",
    "Regions": "المناطق",
    "Organizational units that own datasets": "الوحدات التنظيمية المالكة للمجموعات",
    "Business categories for classifying datasets": "فئات الأعمال لتصنيف المجموعات",
    "Labels for tagging and filtering datasets": "تسميات لوسم وتصفية المجموعات",
    "Geographic regions for datasets": "المناطق الجغرافية للمجموعات",
    // OrgSettings
    "Organization Settings": "إعدادات المؤسسة",
    "Configure departments, categories, tags, and regions used across the platform": "تكوين الأقسام والفئات والعلامات والمناطق المستخدمة في المنصة",
    "Add new value": "إضافة قيمة جديدة",
    "Reset": "إعادة تعيين",
    "Save": "حفظ",
    "No values configured": "لا توجد قيم — أضف بعضها أعلاه",
    "values configured": "قيمة مُكوَّنة",
    "Admin privileges are required to manage organization settings.": "يلزم صلاحيات المسؤول لإدارة إعدادات المؤسسة.",
    // DatasetTable
    "Dataset": "مجموعة البيانات",
    "Category": "الفئة",
    "Rows": "الصفوف",
    "Uploaded": "تاريخ الرفع",
    "datasets shown": "مجموعة بيانات معروضة",
    "No datasets found": "لا توجد مجموعات بيانات",
    "Try adjusting filters": "حاول تعديل الفلاتر أو رفع مجموعة بيانات جديدة",
    "View Insights": "عرض الرؤى",
    "Download File": "تنزيل الملف",
    "Delete": "حذف",
    // Metadata field labels
    "Source": "المصدر",
    "Business Owner": "المالك التجاري",
    "Technical Owner": "المالك التقني",
    "Region": "المنطقة",
    "Frequency": "التكرار",
    "Language": "اللغة",
    "Records": "السجلات",
    "No description": "لا يوجد وصف",
    "Created": "تاريخ الإنشاء",
    "Updated": "آخر تحديث",
    "Description": "الوصف",
    "Tags (comma-separated)": "العلامات (مفصولة بفاصلة)",
    "Data Sensitivity": "حساسية البيانات",
    "Update Frequency": "تكرار التحديث",
    // DataQuality expanded
    "Missing Values": "القيم المفقودة",
    "Duplicate Rows": "الصفوف المكررة",
    "Empty Columns": "الأعمدة الفارغة",
    "Invalid Dates": "التواريخ غير الصالحة",
    "Invalid Numerics": "الأرقام غير الصالحة",
    "Consistency": "الاتساق",
    "Warnings": "التحذيرات",
    "Recommendations": "التوصيات",
    "Last checked": "آخر فحص",
    // Governance KPIs
    "Total Datasets": "إجمالي مجموعات البيانات",
    "Metadata Complete": "اكتمال البيانات الوصفية",
    "Missing Metadata": "بيانات وصفية مفقودة",
    "Quality Reports": "تقارير الجودة",
    "Good Quality": "جودة جيدة",
    "Needs Review": "تحتاج مراجعة",
    "Poor Quality": "جودة رديئة",
    "active": "نشط",
    "fully complete": "مكتملة بالكامل",
    "datasets OK": "مجموعة سليمة",
    "not analyzed": "غير محللة",
    "of analyzed": "من المحللة",
    "Needs immediate action": "تحتاج إجراء فوري",
    "All clear": "كل شيء سليم",
    "Monitor quality, metadata completeness, and catalog health across": "مراقبة جودة البيانات واكتمال البيانات الوصفية وصحة الكتالوج عبر",
    // Governance charts
    "Data Quality Distribution": "توزيع جودة البيانات",
    "Quality status breakdown across all datasets": "تفصيل حالة الجودة عبر جميع المجموعات",
    "No quality reports yet": "لا توجد تقارير جودة بعد",
    "Datasets by Department": "المجموعات حسب القسم",
    "Number of datasets per business unit": "عدد المجموعات لكل وحدة أعمال",
    "No department data yet": "لا توجد بيانات أقسام بعد",
    "Datasets by Category": "المجموعات حسب الفئة",
    "Classification breakdown of the data catalog": "تفصيل تصنيف كتالوج البيانات",
    "No category data yet": "لا توجد بيانات فئات بعد",
    "Missing Metadata Fields": "حقول البيانات الوصفية المفقودة",
    "Datasets missing key metadata per field": "المجموعات التي تفتقر إلى بيانات وصفية أساسية",
    "No datasets yet": "لا توجد مجموعات بعد",
    "Upload your first dataset to start using the governance dashboard": "قم برفع مجموعة البيانات الأولى لك لبدء استخدام لوحة الحوكمة",
    // Insights tabs
    "Data Preview": "معاينة البيانات",
    "Charts": "الرسوم البيانية",
    "Quality Report": "تقرير الجودة",
    "Column Profiles": "ملفات الأعمدة",
    "Sample Data": "بيانات عينة",
    "Versions": "الإصدارات",
    "Data Lineage": "سلسلة البيانات",
    "Back to Datasets": "العودة إلى المجموعات",
    "No dataset selected": "لم يتم اختيار مجموعة بيانات",
    "Select an existing dataset to explore its insights, or upload a new one.": "اختر مجموعة بيانات موجودة لاستكشاف رؤاها أو قم برفع مجموعة جديدة.",
    "Browse Datasets": "تصفح المجموعات",
    "Select a Dataset": "اختر مجموعة بيانات",
    "Dataset not found.": "لم يتم العثور على مجموعة البيانات.",
    // Report types
    "Metadata Report": "تقرير البيانات الوصفية",
    "Data Quality Report": "تقرير جودة البيانات",
    "Dashboard Summary": "ملخص لوحة التحكم",
    "Dataset Profile": "ملف مجموعة البيانات",
    // Report statuses
    "Generated": "تم الإنشاء",
    "Pending": "قيد الانتظار",
    "Failed": "فشل",
    // Activity Log action names
    "User Login": "تسجيل دخول مستخدم",
    "Dataset Uploaded": "رفع مجموعة بيانات",
    "Dataset Updated": "تحديث مجموعة بيانات",
    "Dataset Deleted": "حذف مجموعة بيانات",
    "Metadata Edited": "تعديل البيانات الوصفية",
    "Report Exported": "تصدير تقرير",
    "Quality Check": "فحص الجودة",
    "User Registered": "تسجيل مستخدم جديد",
    "System": "النظام",
    // Dataset status
    "Active": "نشط",
    "Archived": "مؤرشف",
    "Draft": "مسودة",
    "Under Review": "قيد المراجعة",
    // Dashboard Recent Datasets
    "Recently Uploaded": "تم رفعها مؤخراً",
    "Latest additions to the catalog": "أحدث الإضافات إلى الكتالوج",
    // Chart titles and subtitles
    "Datasets by Department": "مجموعات حسب القسم",
    "Number of datasets per business unit": "عدد المجموعات لكل وحدة أعمال",
    "No department data yet": "لا توجد بيانات أقسام بعد",
    "Datasets by Category": "مجموعات حسب الفئة",
    "Classification breakdown of the data catalog": "تفصيل تصنيف كتالوج البيانات",
    "No category data yet": "لا توجد بيانات فئات بعد",
    "Data Quality Distribution": "توزيع جودة البيانات",
    "Quality status breakdown across all datasets": "تفصيل حالة الجودة عبر جميع المجموعات",
    "No quality reports yet": "لا توجد تقارير جودة بعد",
    "Upload Trends": "اتجاهات الرفع",
    "Datasets uploaded & average quality over last 6 months": "المجموعات المرفوعة ومتوسط الجودة في آخر 6 أشهر",
    "Avg Quality": "متوسط الجودة %",
    // Quality statuses
    "Good": "جيد",
    "Needs Review": "يحتاج مراجعة",
    "Poor Quality": "جودة رديئة",
    // Recent Activity
    "Recent Activity": "النشاط الأخير",
    "Latest platform events": "أحدث أحداث المنصة",
    // View All
    "View All": "عرض الكل",
  },
};

export const LanguageContext = createContext({ lang: "en", t: translations.en });

export function useLang() {
  return useContext(LanguageContext);
}